### ISSUE TITLE
Code to estimate parameters in the power law equation and the exchange rate

### ISSUE THREAD

**Issue by swarnakr** [JonasGeiping/dataaugs#1]
Hi, could you point me to the code that estimate parameters a, b, c in the power law equation and the exchange rate? You mention in the paper that you use the Levenberg-Marquardt implementation of MINPACK wrapped in scipy? The scripts for generating figures in your implementation only train the model for different augmentations and number of samples, without estimating the power law function or the exchange rate itself.

**Comment by JonasGeiping** [comment]
Hi, to be more precise, this is just `scipy.optimize.curve_fit`:
```
from scipy.optimize import curve_fit

def f(x, a, b, c):
    return a * x**(-c) + b
    
def f_inv(y, a, b, c):
    return ((y - b) / a)**(-1/c)

def fit_exponential(xdata, ydata):
    #p0 set to vicinity of no_aug baseline (but this is not too crucial)
    p0=[-3.7445937557392126, 1.414934337961835, 0.1539529459766928] 
    [af, bf, cf], cov = curve_fit(f, xdata, ydata, p0=p0, maxfev=64000)
    return [af, bf, cf]
```

Given fitted `augmentation_coeffs` from the augmented training runs and fitted `baseline_coeffs` from the unaugmented trainings runs, the exchange rate is directly plotted as 
```
rates = [f_inv(f(xx, *augmentation_coeffs),*baseline_coeffs)-xx for xx in xeval_extrap]
```
on chosen coordinates (like `xeval_extrap = np.logspace(np.log10(500), np.log10(400_000), num=1000)`)

**Comment by swarnakr** [comment]
Thanks!
